version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./back/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=druiz
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB = druiz

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - postgres

#  back:
#    build: ./back
#    container_name: backend
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres

#  front:
#    build: ./front
#    container_name: front
#    ports:
#      - "8082:8082"
#    depends_on:
#      - back