version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB = cuatroenraya

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL= "admin@admin.com"
      - PGADMIN_DEFAULT_PASSWORD= "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

  back:
    build: ./back
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
